In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [28]:
df = pd.read_csv("steam_games.csv")

C:\Users\jazmin\AppData\Local\Temp\ipykernel_15008\4264565917.py:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("steam_games.csv")

In [3]:
df.head()

,Unnamed: 0,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df = df.drop(columns="Unnamed: 0")

In [30]:
df = df.dropna(how="all")

In [50]:
df.isnull().sum()

publisher       8071
genres          3283
app_name           2
title           2050
url                0
release_date    2067
tags             163
reviews_url        2
specs            670
price           1377
early_access       0
id                 2
developer       3299
dtype: int64

In [31]:
df["developer"].fillna('Unknown')

In [52]:
df.isnull().sum()

publisher          0
genres             0
app_name           0
title              0
url                0
release_date    2067
tags               0
reviews_url        0
specs              0
price           1377
early_access       0
id                 0
developer          0
dtype: int64

In [32]:
df = df.drop(columns=["app_name","publisher","tags","reviews_url","specs","early_access"])

In [31]:
df["price"].value_counts()

price
4.99           4278
9.99           3902
2.99           3429
0.99           2607
1.99           2541
               ...
74.76             1
32.99             1
14.95             1
26.99             1
Free to Use       1
Name: count, Length: 162, dtype: int64

In [8]:
df.isnull().sum()

genres             0
title              0
url                0
release_date    2067
price           1377
id                 0
developer          0
dtype: int64

In [33]:
df = df.dropna()

In [18]:
df.shape

(28820, 7)

## Endpoints

#### * Endpoint 1

In [14]:
preciosdejuegos = df[["id", "price"]]

In [16]:
preciosdejuegos = nuevo_df.reset_index(drop=True)

In [18]:
#Almaceno los precios de los juegos para crear el endpoint 1 en el archivo us
preciosdejuegos.to_csv('preciosdejuegos.csv', index=False)

#### * Endpoint3:

In [16]:
#Cuento la cantidad de géneros por juego que hay y creo un ranking de géneros.

genres = df["genres"].str.split(',').explode().str.strip()
genres = genres.str.replace(r"[\[\]']", '', regex=True)
genre_counts = genres.value_counts().reset_index()
genre_counts.columns = ["genres", "count"]
genre_counts["position"] = range(1, len(genre_counts) + 1)

In [24]:
genre_counts = genre_counts.drop(columns="count")

In [25]:
genre_counts

                        genre  position
0                       Indie         1
1                      Action         2
2                      Casual         3
3                   Adventure         4
4                    Strategy         5
5                  Simulation         6
6                         RPG         7
7                Free to Play         8
8                Early Access         9
9                      Sports        10
10                    Unknown        11
11                     Racing        12
12      Massively Multiplayer        13
13  Design &amp; Illustration        14
14                  Utilities        15
15             Web Publishing        16
16   Animation &amp; Modeling        17
17                  Education        18
18           Video Production        19
19          Software Training        20
20           Audio Production        21
21              Photo Editing        22
22                 Accounting        23

In [26]:
#Lo almaceno en un csv para luego consumirlo desde la API.
genre_counts.to_csv("df_endpoint3.csv", index=False)

#### * Enpoint5 :

In [22]:
df["developer"].value_counts()

developer
Ubisoft - San Francisco       1258
Unknown                       1224
SmiteWorks USA, LLC            812
Dovetail Games                 253
KOEI TECMO GAMES CO., LTD.     215
                              ...
Project Purity Team              1
Triple rush games                1
Storybird,Julien Rocca           1
Light                            1
Bidoniera Games                  1
Name: count, Length: 10632, dtype: int64

In [92]:
df["release_date"] = pd.to_datetime(df["release_date"], errors='coerce') #Hallo los valore de realese_date con mal formato y los quito.
df = df.dropna(subset=["release_date"])

df["año"] = df["release_date"].dt.year  #Creo una columna de año.

contenido_free = df[df["price"] == 0.0] #Selecciono un subset donde los precios sean 0.0.

total_juegos_por_desarrollador = df.groupby(["developer", "año"]).size().reset_index(name="total_juegos") #Agrupo a los juegos por año y desarrollador.
num_juegos_gratuitos = contenido_free.groupby(["developer", "año"]).size().reset_index(name='num_juegos_gratuitos')

juegos_por_desarrollador = total_juegos_por_desarrollador.merge(num_juegos_gratuitos, on=["developer", "año"], how="left") #Uno en un dataframe los juegos free y los demás.
juegos_por_desarrollador["porcentaje_juegos_gratuitos"] = (juegos_por_desarrollador["num_juegos_gratuitos"] / juegos_por_desarrollador["total_juegos"]) * 100 #Calculo el promedio de juegos gratuitos

juegos_por_desarrollador = resultados.fillna(0)
juegos_por_desarrollador["num_juegos_gratuitos"] = juegos_por_desarrollador["num_juegos_gratuitos"].astype(int)
juegos_por_desarrollador["porcentaje_juegos_gratuitos"] = juegos_por_desarrollador["porcentaje_juegos_gratuitos"].apply(lambda x: f'{int(x)}%')

In [93]:
#Chequeo que haya quedado bien.
resuljuegos_por_desarrolladortados[juegos_por_desarrollador["developer"]=="Dovetail Games"]

,developer,year,total_juegos,num_juegos_gratuitos,porcentaje_juegos_gratuitos
3606,Dovetail Games,2009,22,0,0%
3607,Dovetail Games,2010,4,0,0%
3608,Dovetail Games,2011,4,0,0%
3609,Dovetail Games,2012,52,0,0%
3610,Dovetail Games,2013,39,0,0%
3611,Dovetail Games,2014,37,0,0%
3612,Dovetail Games,2015,50,0,0%
3613,Dovetail Games,2016,21,0,0%
3614,Dovetail Games,2017,24,1,4%

In [95]:
#Almaceno el df en un csv para ser consumido por la API.
juegos_por_desarrollador.to_csv("df_endpoint5.csv", index=False)